Remove mypy from battery of tests for the time being
Need to ascertain why this error is happening

> AssertionError: Definition of pydantic.types.JsonValue is unexpectedly incomplete